In [1]:
import pandas as pd
data = pd.read_csv("deliveries.csv")
data.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [2]:
match = pd.read_csv("matches.csv")
match.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,06-04-2017,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,08-04-2017,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,22-05-2016,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,24-05-2016,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,25-05-2016,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,27-05-2016,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,29-05-2016,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [197]:
teams = match.team1.unique()
for team in teams:
    print(team , match[match['team1'] == team].count()[0] +  match[match['team2'] == team].count()[0])

Sunrisers Hyderabad 76
Mumbai Indians 157
Gujarat Lions 30
Rising Pune Supergiant 16
Royal Challengers Bangalore 152
Kolkata Knight Riders 148
Delhi Daredevils 147
Kings XI Punjab 148
Chennai Super Kings 131
Rajasthan Royals 118
Deccan Chargers 75
Kochi Tuskers Kerala 14
Pune Warriors 46
Rising Pune Supergiants 14

In [ ]:
Rising Pune Supergiants 14
Kochi Tuskers Kerala 14
Gujarat Lions 30
Rising Pune Supergiant 16

In [264]:
match = match.replace('Deccan Chargers','Sunrisers Hyderabad')
match = match.replace('Rising Pune Supergiant','Chennai Super Kings')
match =match.replace('Rising Pune Supergiants','Chennai Super Kings')
match = match.replace('Gujarat Lions','Rajasthan Royals')
match = match.replace('Kochi Tuskers Kerala','Rajasthan Royals')
match = match.replace('Pune Warriors','Rajasthan Royals')
match = match.replace('Delhi Daredevils','Delhi Capitals')

match.head(50)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,06-04-2017,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,07-04-2017,Rajasthan Royals,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,08-04-2017,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,09-04-2017,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,2017,Pune,11-04-2017,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Delhi Capitals,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,2017,Mumbai,12-04-2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
10,11,2017,Kolkata,13-04-2017,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN
11,12,2017,Bangalore,14-04-2017,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,KA Pollard,M Chinnaswamy Stadium,KN Ananthapadmanabhan,AK Chaudhary,NaN
12,13,2017,Rajkot,14-04-2017,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,7,AJ Tye,Saurashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
13,14,2017,Kolkata,15-04-2017,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,17,0,RV Uthappa,Eden Gardens,AY Dandekar,NJ Llong,NaN
14,15,2017,Delhi,15-04-2017,Delhi Capitals,Kings XI Punjab,Delhi Capitals,bat,normal,0,Delhi Capitals,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN
15,16,2017,Mumbai,16-04-2017,Rajasthan Royals,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,N Rana,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
16,17,2017,Bangalore,16-04-2017,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Chennai Super Kings,27,0,BA Stokes,M Chinnaswamy Stadium,KN Ananthapadmanabhan,C Shamshuddin,NaN
17,18,2017,Delhi,17-04-2017,Delhi Capitals,Kolkata Knight Riders,Delhi Capitals,bat,normal,0,Kolkata Knight Riders,0,4,NM Coulter-Nile,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN
18,19,2017,Hyderabad,17-04-2017,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN
19,20,2017,Rajkot,18-04-2017,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,normal,0,Royal Challengers Bangalore,21,0,CH Gayle,Saurashtra Cricket Association Stadium,S Ravi,VK Sharma,NaN
20,21,2017,Hyderabad,19-04-2017,Sunrisers Hyderabad,Delhi Capitals,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,15,0,KS Williamson,"Rajiv Gandhi International Stadium, Uppal",CB Gaffaney,NJ Llong,NaN
21,22,2017,Indore,20-04-2017,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,JC Buttler,Holkar Cricket Stadium,M Erasmus,C Shamshuddin,NaN
22,23,2017,Kolkata,21-04-2017,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,4,SK Raina,Eden Gardens,CB Gaffaney,Nitin Menon,NaN
23,24,2017,Mumbai,22-04-2017,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,normal,0,Mumbai Indians,14,0,MJ McClenaghan,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
24,25,2017,Pune,22-04-2017,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,MS Dhoni,Maharashtra Cricket Association Stadium,AY Dandekar,A Deshmukh,NaN
25,26,2017,Rajkot,23-04-2017,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,normal,0,Kings XI Punjab,26,0,HM Amla,Saurashtra Cricket Association Stadium,AK Chaudhary,M Erasmus,NaN
26,27,2017,Kolkata,23-04-2017,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,82,0,NM Coulter-Nile,Eden Gardens,CB Gaffaney,CK Nandan,NaN
27,28,2017,Mumbai,24-04-2017,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,normal,0,Chennai Super Kings,3,0,BA Stokes,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
28,29,2017,Pune,26-04-2017,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,RV Uthappa,Maharashtra Cricket Association Stadium,AY Dandekar,NJ Llong,NaN
29,30,2017,Bangalore,27-04-2017,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,7,AJ Tye,M Chinnaswamy Stadium,AK Chaudhary,C Shamshuddin,NaN
30,31,2017,Kolkata,28-04-2017,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,G Gambhir,Eden Gardens,NJ Llong,S Ravi,NaN
31,32,2017,Chandigarh,28-04-2017,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,26,0,Rashid Khan,"Punjab Cricket Association IS Bindra Stadium, ...",Nitin Menon,CK Nandan,NaN
32,33,2017,Pune,29-04-2017,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Chennai Super Kings,61,0,LH Ferguson,Maharashtra Cricket Association Stadium,KN Ananthapadmanabhan,M Erasmus,NaN
33,34,2017,Rajkot,29-04-2017,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,bat,tie,0,Mumbai Indians,0,0,KH Pandya,Saurashtra Cricket Association Stadium,AK Chaudhary,CB Gaffaney,NaN
34,35,2017,Chandigarh,30-04-2017,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,10,Sandeep Sharma,"Punjab Cricket Association IS Bindra Stadium, ...",YC Barde,CK Nandan,NaN
35,36,2017,Hyderabad,30-04-2017,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,48,0,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,S Ravi,NaN
36,37,2017,Mumbai,01-05-2017,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,bat,normal,0,Mumbai Indians,0,5,RG Sharma,Wankhede Stadium,AK Chaudhary,CB Gaffaney,NaN
37,38,2017,Pune,01-05-2017,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,5,BA Stokes,Maharashtra Cricket Association Stadium,M Erasmus,C Shamshuddin,NaN
38,39,2017,Delhi,02-05-2017,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,6,Mohammed Shami,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN
39,40,2017,Kolkata,03-05-2017,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,4,RA Tripathi,Eden Gardens,KN Ananthapadmanabhan,A Nand Kishore,NaN
40,41,2017,Delhi,04-05-2017,Rajasthan Royals,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,7,RR Pant,Feroz Shah Kotla,M Erasmus,Nitin Menon,NaN
41,42,2017,Bangalore,05-05-2017,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kings XI Punjab,19,0,Sandeep Sharma,M Chinnaswamy Stadium,CB Gaffaney,C Shamshuddin,NaN
42,43,2017,Hyderabad,06-05-2017,Chennai Super Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Chennai Super Kings,12,0,JD Unadkat,"Rajiv Gandhi International Stadium, Uppal",KN Ananthapadmanabhan,AK Chaudhary,NaN
43,44,2017,Delhi,06-05-2017,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,normal,0,Mumbai Indians,146,0,LMP Simmons,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN
44,45,2017,Bangalore,07-05-2017,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,6,SP Narine,M Chinnaswamy Stadium,AY Dandekar,C Shamshuddin,NaN
45,46,2017,Chandigarh,07-05-2017,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,6,DR Smith,"Punjab Cricket Association IS Bindra Stadium, ...",A Nand Kishore,VK Sharma,NaN
46,47,2017,Hyderabad,08-05-2017,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,normal,0,Sunrisers Hyderabad,0,7,S Dhawan,"Rajiv Gandhi International Stadium, Uppal",KN Ananthapadmanabhan,M Erasmus,NaN
47,48,2017,Chandigarh,09-05-2017,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kings XI Punjab,14,0,MM Sharma,"Punjab Cricket Association IS Bindra Stadium, ...",A Nand Kishore,S Ravi,NaN
48,49,2017,Kanpur,10-05-2017,Rajasthan Royals,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,SS Iyer,Green Park,YC Barde,AK Chaudhary,NaN
49,50,2017,Mumbai,11-05-2017,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Kings XI Punjab,7,0,WP Saha,Wankhede Stadium,A Deshmukh,A Nand Kishore,NaN

In [265]:
data.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000
mean,318.281317,1.482188,10.142649,3.616483,0.000538,0.037498,0.004885,0.022232,0.004340,0.000066,1.222445,0.069022,1.291466
std,182.955531,0.501768,5.674338,1.807698,0.023196,0.257398,0.114234,0.200104,0.072652,0.018229,1.594509,0.349667,1.583240
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,161.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,319.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,476.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,636.000000,4.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,6.000000,7.000000,7.000000

In [266]:
null_counts = data.isnull().sum()
null_counts

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    143022
dismissal_kind      143022
fielder             145091
dtype: int64

In [267]:
uven = match["venue"].unique()
uven

array(['Rajiv Gandhi International Stadium, Uppal',
       'Maharashtra Cricket Association Stadium',
       'Saurashtra Cricket Association Stadium', 'Holkar Cricket Stadium',
       'M Chinnaswamy Stadium', 'Wankhede Stadium', 'Eden Gardens',
       'Feroz Shah Kotla',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Green Park', 'Punjab Cricket Association Stadium, Mohali',
       'Sawai Mansingh Stadium', 'MA Chidambaram Stadium, Chepauk',
       'Dr DY Patil Sports Academy', 'Newlands', "St George's Park",
       'Kingsmead', 'SuperSport Park', 'Buffalo Park',
       'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium'],
      dtype=object)

In [268]:
match["venue"].describe()

count                       636
unique                       35
top       M Chinnaswamy Stadium
freq                         66
Name: venue, dtype: object

In [269]:
match["city"].describe()

count        629
unique        30
top       Mumbai
freq          85
Name: city, dtype: object

In [270]:
ucity = match["city"].unique()
ucity

array(['Hyderabad', 'Pune', 'Rajkot', 'Indore', 'Bangalore', 'Mumbai',
       'Kolkata', 'Delhi', 'Chandigarh', 'Kanpur', 'Jaipur', 'Chennai',
       'Cape Town', 'Port Elizabeth', 'Durban', 'Centurion',
       'East London', 'Johannesburg', 'Kimberley', 'Bloemfontein',
       'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala', 'Kochi',
       'Visakhapatnam', 'Raipur', 'Ranchi', 'Abu Dhabi', 'Sharjah', nan],
      dtype=object)

In [271]:
ut1 = match["team2"].unique()
ut1

array(['Royal Challengers Bangalore', 'Chennai Super Kings',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Capitals',
       'Sunrisers Hyderabad', 'Mumbai Indians', 'Rajasthan Royals'],
      dtype=object)

In [272]:
#X = match[['team1', 'team2', 'toss_decision','toss_winner','venue','winner']]
X = match[['team1', 'team2', 'toss_decision','toss_winner','venue',]]
X.head()

,team1,team2,toss_decision,toss_winner,venue
0,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal"
1,Mumbai Indians,Chennai Super Kings,field,Chennai Super Kings,Maharashtra Cricket Association Stadium
2,Rajasthan Royals,Kolkata Knight Riders,field,Kolkata Knight Riders,Saurashtra Cricket Association Stadium
3,Chennai Super Kings,Kings XI Punjab,field,Kings XI Punjab,Holkar Cricket Stadium
4,Royal Challengers Bangalore,Delhi Capitals,bat,Royal Challengers Bangalore,M Chinnaswamy Stadium

In [273]:
Y = match[['winner']]
Y.head()

                        winner
0          Sunrisers Hyderabad
1          Chennai Super Kings
2        Kolkata Knight Riders
3              Kings XI Punjab
4  Royal Challengers Bangalore

In [274]:
dummies = pd.get_dummies(match.toss_decision)
dummies

     bat  field
0      0      1
1      0      1
2      0      1
3      0      1
4      1      0
..   ...    ...
631    0      1
632    0      1
633    0      1
634    0      1
635    1      0

[636 rows x 2 columns]

In [275]:
df_encoded = pd.get_dummies(X, columns=['team1', 'team2', 'toss_decision', 'toss_winner', 'venue'])
df_encoded.head(30)

,team1_Chennai Super Kings,team1_Delhi Capitals,team1_Kings XI Punjab,team1_Kolkata Knight Riders,team1_Mumbai Indians,team1_Rajasthan Royals,team1_Royal Challengers Bangalore,team1_Sunrisers Hyderabad,team2_Chennai Super Kings,team2_Delhi Capitals,...,venue_Saurashtra Cricket Association Stadium,venue_Sawai Mansingh Stadium,venue_Shaheed Veer Narayan Singh International Stadium,venue_Sharjah Cricket Stadium,venue_Sheikh Zayed Stadium,venue_St George's Park,venue_Subrata Roy Sahara Stadium,venue_SuperSport Park,"venue_Vidarbha Cricket Association Stadium, Jamtha",venue_Wankhede Stadium
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
10,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
21,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
24,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
26,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [276]:
y1 = pd.get_dummies(Y.winner)
y1

,Chennai Super Kings,Delhi Capitals,Kings XI Punjab,Kolkata Knight Riders,Mumbai Indians,Rajasthan Royals,Royal Challengers Bangalore,Sunrisers Hyderabad
0,0,0,0,0,0,0,0,1
1,1,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...
631,0,0,0,0,0,0,1,0
632,0,0,0,0,0,0,1,0
633,0,0,0,0,0,0,0,1
634,0,0,0,0,0,0,0,1
635,0,0,0,0,0,0,0,1

In [277]:
y1.head(30)

,Chennai Super Kings,Delhi Capitals,Kings XI Punjab,Kolkata Knight Riders,Mumbai Indians,Rajasthan Royals,Royal Challengers Bangalore,Sunrisers Hyderabad
0,0,0,0,0,0,0,0,1
1,1,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,1,0
5,0,0,0,0,0,0,0,1
6,0,0,0,0,1,0,0,0
7,0,0,1,0,0,0,0,0
8,0,1,0,0,0,0,0,0
9,0,0,0,0,1,0,0,0
10,0,0,0,1,0,0,0,0
11,0,0,0,0,1,0,0,0
12,0,0,0,0,0,1,0,0
13,0,0,0,1,0,0,0,0
14,0,1,0,0,0,0,0,0
15,0,0,0,0,1,0,0,0
16,1,0,0,0,0,0,0,0
17,0,0,0,1,0,0,0,0
18,0,0,0,0,0,0,0,1
19,0,0,0,0,0,0,1,0
20,0,0,0,0,0,0,0,1
21,0,0,0,0,1,0,0,0
22,0,0,0,0,0,1,0,0
23,0,0,0,0,1,0,0,0
24,1,0,0,0,0,0,0,0
25,0,0,1,0,0,0,0,0
26,0,0,0,1,0,0,0,0
27,1,0,0,0,0,0,0,0
28,0,0,0,1,0,0,0,0
29,0,0,0,0,0,1,0,0

In [300]:
from sklearn.linear_model import LogisticRegression
import numpy as np
# Create a logistic regression model
model = LogisticRegression()
y_1d = np.argmax(y1.values, axis=1)
# Fit the model using X_encoded as the features and y_encoded as the target variable
model.fit(df_encoded, y_1d)

# Print the trained model's coefficients/weights
print("Coefficients:", model.coef_)

# Print the trained model's intercept/constant term
print("Intercept:", model.intercept_)

Coefficients: [[ 2.80443407e+00 -3.61123435e-02 -5.12012269e-01 -1.25304426e-01
  -4.85849070e-01 -3.57982409e-01 -7.04459056e-01 -5.82467597e-01
   3.02046835e+00 -5.54945356e-01 -4.65475114e-01 -7.92869418e-01
  -3.93904751e-01 -2.81379781e-01 -2.70958251e-01 -2.60688787e-01
   1.02389836e-03 -7.77001624e-04  5.50738447e-01 -9.22995510e-03
  -3.37077387e-01  2.16345911e-01 -1.72438916e-01 -2.57862920e-02
   1.39573554e-02 -2.36262266e-01 -4.63103759e-01  1.25216709e-01
   2.04552739e-01  2.87395987e-01  2.59304707e-01  4.09904137e-01
   6.20090527e-01 -4.73071499e-03  2.70121014e-01 -6.32839034e-02
   1.63314196e-01 -2.33683911e-01  2.25523594e-01 -5.26679214e-01
   1.98344144e-01  6.72889643e-01 -1.58688121e-01 -3.52742397e-01
   4.57382600e-02 -4.63429131e-01 -4.79807154e-02 -5.56711755e-01
   3.42486543e-01  2.07974501e-01 -6.33010046e-01 -7.55619468e-01
   1.77962755e-01 -3.98973995e-01  2.91704785e-01 -7.41750745e-02
   5.51320069e-01 -4.23332695e-01  2.61489894e-01 -5.36178461e-01
   3.77236054e-01]
 [-5.13853872e-01  2.40269311e+00 -2.54382752e-02 -2.34557299e-01
  -4.30843391e-01 -3.22237428e-01 -7.60629699e-01 -1.15210968e-01
  -1.75218506e-01  2.94681070e+00 -6.99104066e-01 -5.28227618e-01
  -3.69647572e-01 -5.01408892e-01 -4.05292363e-01 -2.67989504e-01
   4.00430758e-02 -4.01208936e-02  1.06015313e-01  3.33329193e-01
  -1.90000962e-01 -8.04769233e-02  5.96766384e-01 -6.00751113e-02
  -3.23870047e-01 -3.81765663e-01 -2.80163525e-01 -7.08332533e-01
   3.20853135e-01 -3.77711030e-02 -7.22801817e-02 -9.08466715e-02
   4.61023604e-02 -4.43992741e-01  2.05945776e-01  3.02321450e-01
  -3.59524049e-01 -3.75007588e-02 -7.05091572e-02  8.93541194e-01
  -3.81717210e-03 -6.66833032e-02  5.62414579e-01  3.90326135e-01
  -3.55766446e-01  2.59048963e-01  3.10709093e-01 -6.24895925e-01
  -1.59152682e-01  1.20900187e-01 -7.27432264e-02  1.82734167e-01
  -1.37830270e-02  6.50184882e-01  6.19279548e-02 -3.32706865e-01
   3.97396061e-01 -3.08994797e-01  1.01192398e-01 -3.67057784e-02
  -7.29506211e-01]
 [-4.57399435e-01  1.30073306e-01  2.92475421e+00 -7.02403829e-01
  -6.36379866e-01 -5.81148685e-01 -1.27490311e-01 -5.49849504e-01
  -2.66429641e-01 -7.80681860e-01  3.22893660e+00 -4.02962758e-01
  -3.88582869e-01 -3.89257729e-01 -4.62504923e-01 -5.38360934e-01
  -3.01447438e-01  3.01603321e-01 -6.07635107e-02  6.46292693e-03
  -3.39980905e-01  1.10375418e-01  2.84441932e-01 -1.75484487e-01
   2.38839056e-01 -6.37345479e-02 -8.58527991e-02 -4.15976377e-01
  -2.38661867e-02  4.26657169e-01 -3.91971956e-01  6.14712082e-02
   2.29637333e-01 -1.81528998e-01 -6.04729285e-01 -4.69809334e-02
   4.01974668e-01  3.33518943e-01 -1.12970942e-01 -3.33798418e-01
  -3.94164701e-01  6.55287969e-02 -8.78119632e-01 -7.69034593e-02
   3.74975486e-01  1.95182955e-01  1.55834697e-01 -2.43128913e-01
   1.70442953e-01  7.02200182e-02  3.39616003e-01  5.15907350e-01
  -6.55229021e-01 -9.78806846e-02  4.75449413e-01  7.33405476e-01
   3.15052115e-01 -4.70460208e-02 -5.08436979e-01 -2.88901923e-02
   2.62756794e-01]
 [-1.39352192e-01 -2.25461392e-01 -2.19708529e-01  2.37754451e+00
  -6.35321559e-01 -5.12342615e-01 -1.52018964e-01 -4.93829957e-01
  -1.24505346e+00 -3.50872699e-01 -3.19254206e-01  3.23554763e+00
  -5.76844231e-01 -6.13427255e-01 -1.84324522e-01  5.37380489e-02
   1.95440411e-01 -1.95931106e-01 -4.95863981e-02  3.16950006e-02
   1.19146016e-01  4.13629212e-01 -3.85843905e-01 -5.14982475e-01
  -7.20583080e-02  4.57510162e-01  9.41411501e-01 -3.46464284e-01
  -2.42149827e-01 -2.90059526e-02  4.53583396e-01 -4.25891618e-01
  -3.38496383e-01  1.11467901e+00  1.56986876e-02 -9.09727073e-02
  -9.13034328e-02 -3.85637725e-02 -4.23569812e-01  1.01819868e-01
   4.07203383e-01 -2.04973016e-01  5.68842515e-01 -4.21900545e-01
  -4.74202243e-01 -6.59997082e-01 -2.77271396e-02 -8.41055398e-02
  -2.06572559e-01  5.59291939e-02 -4.37208529e-01  2.73269891e-01
  -8.88291773e-02 -2.66206552e-01  5.61161700e-01  7.55456531e-02
  -4.75081851e-01  7.65271239e-01  1.43875332e-01 -4.16763338e-02
  -6.38837108e-02]
 [-5.15812854e-01 -7.04691444e-01 -5.69136433e-01 -2.13322665e-01
   3.30561812e+00 -3.91413475e-01 -4.29974805e-01 -4.81318073e-01
  -3.03668146e-01 -5.35561839e-01 -5.77040889e-01 -2.32439035e-01
   3.24710841e+00 -4.78732472e-01 -5.33554206e-01 -5.86163442e-01
   2.69968255e-02 -2.70484500e-02 -2.69366968e-01  4.72039816e-01
   2.45102544e-01 -2.16398140e-01 -6.40517346e-02  9.21414505e-02
  -2.54607994e-01 -4.91059771e-03 -2.96882235e-01  7.22997053e-01
  -9.56038743e-03 -4.15017738e-02  4.58658030e-01 -3.02539650e-02
  -7.02450442e-01  8.20622569e-01 -4.60535256e-01 -3.90256023e-01
  -2.72795133e-01  5.50109060e-01 -7.75860379e-02 -1.01644582e+00
   5.06454123e-01  1.87712987e-01 -2.53559464e-02 -6.59367374e-02
  -3.56104029e-01  3.55086815e-01 -2.99917743e-02  2.23899818e-01
   8.91223108e-02  2.61603532e-01 -3.27290104e-02  1.66615770e-01
   4.34147025e-02 -5.51273068e-02 -3.44155928e-01 -4.89455429e-01
   1.11692174e-01  2.34237199e-01 -4.77841072e-01 -2.48675367e-02
   4.67554077e-01]
 [-1.25917166e-01 -5.90250711e-01 -4.22726747e-01 -1.63200313e-01
  -4.83333616e-01  2.47267989e+00 -4.62919757e-01 -2.24308275e-01
  -4.51550175e-01 -1.41637633e-01 -1.17714512e-01  1.96654744e-01
  -6.76098914e-01  2.88929929e+00 -8.71750179e-01 -8.27179321e-01
   6.74175570e-02 -6.73942509e-02 -1.76934519e-02 -1.00835346e-01
   1.16690807e-01 -6.48475332e-02 -2.18834482e-01  4.74041624e-01
  -8.82493475e-02 -1.00248964e-01 -3.07840262e-01  6.70260527e-02
  -3.70370570e-02 -5.36738158e-01 -3.00144195e-01  2.32282423e-01
  -3.95702425e-01 -2.33123192e-01  2.59874154e-01  1.88518253e-01
  -8.91396082e-02 -2.69637710e-01  5.83330734e-02  2.75739915e-01
  -1.31731551e-01 -4.01517378e-01  1.10617894e-01 -6.41002436e-02
  -8.70348958e-02 -2.43570017e-01 -3.09702485e-01  4.62545608e-01
  -8.07748519e-02 -1.88071474e-01  5.76025093e-01 -2.66633851e-01
   9.69183441e-01 -4.37496354e-01 -2.75368948e-01  6.61263190e-01
   2.93659308e-01 -7.57049449e-01  2.87747906e-01  5.88783720e-01
   3.80837381e-01]
 [-4.69593573e-01 -5.94700306e-01 -7.07244930e-01 -1.55635781e-01
  -3.43575243e-01 -1.65959476e-01  2.90576748e+00 -4.69093206e-01
  -1.90404083e-01 -1.37802860e-01 -6.41487653e-01 -8.27516869e-01
  -5.07201116e-01 -2.42740853e-01  3.06182842e+00 -5.14710026e-01
   5.29647054e-02 -5.29997411e-02  5.16884945e-02 -1.10413433e-01
   2.20264068e-01 -6.71351392e-01 -7.60672778e-02  2.60859593e-01
   1.33324465e-01  1.91660447e-01 -5.70035420e-02  4.23433065e-01
  -3.10400304e-02 -5.90067685e-02 -7.03805574e-02 -1.22373245e-01
   3.46504624e-02 -1.33033823e-01  1.84751762e-01 -7.34365813e-02
  -4.39997648e-01 -2.36754593e-01  7.81067307e-02  5.84776449e-01
   9.04623118e-02 -2.87912654e-01  2.11989435e-01  1.93662849e-01
   5.56950991e-01 -1.05313531e-02 -2.51857273e-02  4.06749591e-01
  -7.22909373e-03 -5.24779713e-01  1.36037474e-01 -1.62422687e-01
   2.03298054e-01  3.23016156e-01 -1.52243176e-01 -3.14502471e-01
  -7.95228658e-01  2.12686833e-01  2.26778475e-01 -2.63735448e-01
  -1.00587905e-01]
 [-5.82504976e-01 -3.81550223e-01 -4.68487023e-01 -7.83120200e-01
  -2.90315379e-01 -1.41595801e-01 -2.68274889e-01  2.91607758e+00
  -3.88144344e-01 -4.45308457e-01 -4.08860158e-01 -6.48186673e-01
  -3.34828953e-01 -3.82352312e-01 -3.33443980e-01  2.94135396e+00
  -8.24390347e-02  8.26681225e-02 -3.11031925e-01 -6.23048202e-01
   1.65855818e-01  2.92723447e-01  3.60279992e-02 -5.07143024e-02
   3.52664822e-01  1.37751431e-01  5.49434621e-01  1.32100314e-01
  -1.81752385e-01 -1.00294000e-02 -3.36769244e-01 -3.42922691e-02
   5.06168568e-01 -9.38892113e-01  1.28873147e-01  1.74090445e-01
   6.87471007e-01 -6.74872582e-02  3.22672551e-01  2.10460293e-02
  -6.72750538e-01  3.49549255e-02 -3.91700724e-01  3.97594397e-01
   2.95442875e-01  5.68208851e-01 -2.59559481e-02  4.15647116e-01
  -1.48322621e-01 -3.77624596e-03  1.24012241e-01  4.61488284e-02
  -6.36017728e-01  2.82483853e-01 -6.18475800e-01 -2.59374480e-01
  -3.98809217e-01  3.24227690e-01 -3.48059531e-02  3.43270030e-01
  -5.94406480e-01]]
Intercept: [ 0.17071385 -0.06146476  0.08265421 -0.25315933  0.00924551 -0.05155741
 -0.01374807  0.11731599]

In [346]:
arr = df_encoded.iloc[4].values
# arr = arr.reshape(-1, 1)

In [347]:
arr

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [348]:

predictions = model.predict([arr])
team_mapping = {
    0: "Chennai Super Kings",
    1: "Delhi Capitals",
    2: "Kings XI Punjab",
    3 :"Kolkata Knight Riders",
    4: "Mumbai Indians",
    5: "Rajasthan Royals",
    6: "Royal Challengers Bangalore",
    7: "Sunrisers Hyderabad",

}

# Replace numbers with team names in predictions
predictions = [team_mapping[pred] if pred in team_mapping else pred for pred in predictions]

# Print the predictions
print(predictions)

['Royal Challengers Bangalore']

C:\Users\Kush-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [349]:
model.score(df_encoded,y_1d)

0.7547169811320755

In [350]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [351]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_encoded,y_1d,test_size=0.2)

In [352]:
X_train, X_test, y_train, y_test

(     team1_Chennai Super Kings  team1_Delhi Capitals  team1_Kings XI Punjab  \
 616                          0                     0                      0
 108                          0                     0                      0
 87                           0                     0                      0
 478                          0                     0                      1
 576                          0                     0                      0
 ..                         ...                   ...                    ...
 416                          0                     0                      0
 196                          0                     1                      0
 486                          0                     0                      0
 357                          0                     0                      0
 34                           0                     1                      0

      team1_Kolkata Knight Riders  team1_Mumbai Indians  \
 616                            0                     0
 108                            0                     1
 87                             1                     0
 478                            0                     0
 576                            0                     1
 ..                           ...                   ...
 416                            0                     1
 196                            0                     0
 486                            0                     0
 357                            0                     0
 34                             0                     0

      team1_Rajasthan Royals  team1_Royal Challengers Bangalore  \
 616                       0                                  1
 108                       0                                  0
 87                        0                                  0
 478                       0                                  0
 576                       0                                  0
 ..                      ...                                ...
 416                       0                                  0
 196                       0                                  0
 486                       0                                  0
 357                       1                                  0
 34                        0                                  0

      team1_Sunrisers Hyderabad  team2_Chennai Super Kings  \
 616                          0                          0
 108                          0                          0
 87                           0                          0
 478                          0                          0
 576                          0                          1
 ..                         ...                        ...
 416                          0                          0
 196                          0                          0
 486                          1                          0
 357                          0                          0
 34                           0                          0

      team2_Delhi Capitals  ...  venue_Saurashtra Cricket Association Stadium  \
 616                     0  ...                                             0
 108                     1  ...                                             0
 87                      0  ...                                             0
 478                     0  ...                                             0
 576                     0  ...                                             0
 ..                    ...  ...                                           ...
 416                     0  ...                                             0
 196                     0  ...                                             0
 486                     0  ...                                             0
 357                     0  ...                                             0
 34                      0  ...                                             0

      venue_Sawai Mansingh Stadium  \
 616                             0
 108                             0
 87                              0
 478                             0
 576                             0
 ..                            ...
 416                             0
 196                             0
 486                             0
 357                             0
 34                              0

      venue_Shaheed Veer Narayan Singh International Stadium  \
 616                                                  0
 108                                                  0
 87                                                   0
 478                                                  0
 576                                                  0
 ..                                                 ...
 416                                                  0
 196                                                  0
 486                                                  0
 357                                                  0
 34                                                   0

      venue_Sharjah Cricket Stadium  venue_Sheikh Zayed Stadium  \
 616                              0                           0
 108                              0                           0
 87                               0                           0
 478                              0                           0
 576                              0                           0
 ..                             ...                         ...
 416                              0                           0
 196                              0                           0
 486                              0                           0
 357                              0                           0
 34                               0                           0

      venue_St George's Park  venue_Subrata Roy Sahara Stadium  \
 616                       0                                 0
 108                       0                                 0
 87                        0                                 0
 478                       0                                 0
 576                       0                                 0
 ..                      ...                               ...
 416                       0                                 0
 196                       0                                 0
 486                       0                                 0
 357                       0                                 1
 34                        0                                 0

      venue_SuperSport Park  \
 616                      0
 108                      0
 87                       0
 478                      0
 576                      0
 ..                     ...
 416                      0
 196                      0
 486                      0
 357                      0
 34                       0

      venue_Vidarbha Cricket Association Stadium, Jamtha  \
 616                                                  0
 108                                                  0
 87                                                   0
 478                                                  0
 576                                                  0
 ..                                                 ...
 416                                                  0
 196                                                  0
 486                                                  0
 357                                                  0
 34                                                   0

      venue_Wankhede Stadium
 616                       0
 108                       0
 87                        0
 478                       1
 576                       1
 ..                      ...
 416                       1
 196                       0
 486                       0
 357                       0
 34                        0

 [508 rows x 61 columns],
      team1_Chennai Super Kings  team1_Delhi Capitals  team1_Kings XI Punjab  \
 330                          0                     0                      0
 40                           0                     0                      0
 455                          0                     0                      0
 51                           0                     0                      0
 221                          0                     0                      0
 ..                         ...                   ...                    ...
 620                          1                     0                      0
 434                          1                     0                      0
 551                          0                     0                      0
 378                          1                     0                      0
 186                          0                     0                      0

      team1_Kolkata Knight Riders  team1_Mumbai Indians  \
 330                            0                     0
 40                             0                     0
 455                            0                     0
 51                             0                     0
 221                            1                     0
 ..                           ...                   ...
 620                            0                     0
 434                            0                     0
 551                            0                     1
 378                            0                     0
 186                            0                     0

      team1_Rajasthan Royals  team1_Royal Challengers Bangalore  \
 330                       0                                  0
 40                        1                                  0
 455                       1                                  0
 51                        1                                  0
 221                       0                                  0
 ..                      ...                                ...
 620                       0                                  0
 434                       0                                  0
 551                       0                                  0
 378                       0                                  0
 186                       1                                  0

      team1_Sunrisers Hyderabad  team2_Chennai Super Kings  \
 330                          1                          0
 40                           0                          0
 455                          0                          0
 51                           0                          0
 221                          0                          1
 ..                         ...                        ...
 620                          0                          0
 434                          0                          0
 551                          0                          0
 378                          0                          0
 186                          0                          0

      team2_Delhi Capitals  ...  venue_Saurashtra Cricket Association Stadium  \
 330                     1  ...                                             0
 40                      1  ...                                             0
 455                     0  ...                                             0
 51                      0  ...                                             0
 221                     0  ...                                             0
 ..                    ...  ...                                           ...
 620                     0  ...                                             0
 434                     0  ...                                             0
 551                     0  ...                                             0
 378                     0  ...                                             0
 186                     0  ...                                             0

      venue_Sawai Mansingh Stadium  \
 330                             0
 40                              0
 455                             0
 51                              0
 221                             0
 ..                            ...
 620                             0
 434                             0
 551                             0
 378                             0
 186                             0

      venue_Shaheed Veer Narayan Singh International Stadium  \
 330                                                  0
 40                                                   0
 455                                                  0
 51                                                   0
 221                                                  0
 ..                                                 ...
 620                                                  0
 434                                                  0
 551                                                  0
 378                                                  0
 186                                                  0

      venue_Sharjah Cricket Stadium  venue_Sheikh Zayed Stadium  \
 330                              0                           0
 40                               0                           0
 455                              0                           0
 51                               0                           0
 221                              0                           0
 ..                             ...                         ...
 620                              0                           0
 434                              0                           0
 551                              0                           0
 378                              0                           0
 186                              0                           0

      venue_St George's Park  venue_Subrata Roy Sahara Stadium  \
 330                       0                                 0
 40                        0                                 0
 455                       0                                 0
 51                        0                                 0
 221                       0                                 0
 ..                      ...                               ...
 620                       0                                 0
 434                       0                                 0
 551                       0                                 0
 378                       0                                 0
 186                       0                                 0

      venue_SuperSport Park  \
 330                      0
 40                       0
 455                      0
 51                       0
 221                      0
 ..                     ...
 620                      0
 434                      0
 551                      0
 378                      0
 186                      0

      venue_Vidarbha Cricket Association Stadium, Jamtha  \
 330                                                  0
 40                                                   0
 455                                                  0
 51                                                   0
 221                                                  0
 ..                                                 ...
 620                                                  0
 434                                                  0
 551                                                  0
 378                                                  0
 186                                                  0

      venue_Wankhede Stadium
 330                       0
 40                        0
 455                       0
 51                        0
 221                       0
 ..                      ...
 620                       0
 434                       0
 551                       0
 378                       0
 186                       0

 [128 rows x 61 columns],
 array([4, 1, 3, 4, 0, 3, 2, 4, 5, 0, 5, 6, 5, 1, 0, 7, 4, 1, 0, 4, 2, 0,
        0, 5, 5, 2, 4, 1, 6, 0, 2, 1, 7, 3, 6, 4, 3, 5, 2, 3, 0, 1, 1, 7,
        0, 6, 1, 6, 7, 2, 5, 5, 4, 1, 0, 5, 7, 0, 3, 3, 4, 6, 1, 4, 2, 7,
        3, 6, 7, 6, 2, 2, 3, 4, 3, 4, 7, 7, 0, 2, 0, 0, 7, 7, 0, 1, 5, 4,
        0, 5, 6, 1, 7, 4, 1, 5, 6, 5, 0, 5, 1, 0, 0, 7, 4, 5, 5, 1, 0, 0,
        7, 2, 7, 5, 7, 2, 6, 4, 2, 2, 4, 3, 1, 5, 6, 7, 7, 6, 5, 6, 6, 4,
        3, 6, 5, 3, 6, 7, 4, 3, 1, 7, 4, 0, 7, 7, 2, 1, 0, 4, 7, 1, 3, 5,
        4, 6, 3, 4, 5, 5, 1, 7, 2, 0, 0, 4, 3, 7, 6, 5, 5, 6, 4, 7, 4, 5,
        7, 2, 5, 7, 2, 7, 2, 0, 7, 3, 1, 7, 3, 5, 2, 4, 4, 0, 5, 5, 7, 1,
        4, 2, 1, 0, 0, 5, 4, 7, 6, 4, 6, 4, 1, 7, 3, 7, 5, 6, 4, 4, 0, 4,
        2, 2, 6, 0, 6, 2, 0, 3, 3, 4, 7, 2, 4, 5, 2, 0, 3, 4, 5, 0, 3, 5,
        0, 0, 6, 2, 7, 6, 3, 5, 4, 5, 0, 7, 3, 4, 7, 5, 1, 6, 7, 3, 4, 5,
        4, 2, 5, 7, 1, 1, 4, 0, 0, 1, 7, 0, 5, 6, 3, 7, 3, 4, 3, 0, 0, 5,
        1, 4, 3, 6, 1, 0, 1, 7, 3, 6, 3, 3, 1, 3, 0, 3, 0, 4, 1, 5, 1, 6,
        0, 0, 3, 3, 6, 0, 5, 6, 7, 6, 5, 4, 3, 5, 6, 2, 0, 4, 0, 6, 1, 5,
        4, 7, 6, 7, 2, 4, 0, 4, 2, 4, 3, 2, 7, 4, 5, 0, 0, 0, 2, 0, 5, 2,
        7, 4, 0, 2, 3, 5, 3, 5, 6, 1, 6, 6, 6, 0, 7, 3, 6, 0, 6, 5, 3, 0,
        0, 0, 6, 5, 0, 2, 4, 2, 6, 0, 4, 3, 3, 6, 4, 4, 6, 1, 7, 5, 4, 2,
        2, 0, 5, 5, 0, 5, 3, 5, 5, 4, 6, 2, 4, 6, 3, 6, 6, 1, 1, 5, 5, 3,
        2, 4, 3, 2, 3, 3, 0, 6, 2, 4, 1, 5, 0, 1, 5, 2, 7, 6, 6, 7, 2, 6,
        7, 1, 5, 4, 4, 5, 2, 3, 1, 0, 6, 1, 7, 7, 5, 0, 2, 0, 7, 0, 4, 0,
        7, 2, 4, 4, 5, 3, 1, 6, 7, 2, 0, 7, 5, 7, 0, 4, 1, 6, 1, 5, 2, 2,
        5, 0, 3, 1, 3, 0, 3, 5, 7, 3, 6, 3, 5, 7, 6, 2, 6, 2, 0, 4, 1, 7,
        5, 2], dtype=int64),
 array([1, 1, 4, 7, 0, 5, 4, 1, 4, 5, 4, 4, 7, 5, 0, 7, 3, 4, 6, 2, 2, 0,
        5, 5, 4, 0, 0, 4, 3, 5, 3, 6, 6, 4, 3, 5, 1, 5, 4, 5, 5, 6, 3, 2,
        3, 0, 5, 1, 3, 6, 6, 5, 4, 5, 0, 5, 4, 4, 4, 5, 2, 1, 4, 4, 2, 4,
        0, 2, 2, 4, 2, 1, 6, 0, 2, 3, 2, 0, 1, 6, 5, 3, 1, 5, 4, 6, 4, 1,
        3, 4, 7, 0, 0, 5, 5, 3, 0, 6, 1, 7, 3, 2, 2, 2, 3, 2, 6, 1, 3, 0,
        7, 0, 2, 3, 0, 0, 6, 1, 3, 7, 5, 2, 3, 3, 0, 4, 0, 5], dtype=int64))

In [353]:
lr = LogisticRegression(   penalty='l2',  C=3.0,  max_iter=1000,verbose=1,n_jobs=5)
lr.fit(X_train, y_train)
lr.predict([arr])
# lr.score(X_test, y_test)

[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   1 out of   1 | elapsed:    1.2s finished
C:\Users\Kush-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([6], dtype=int64)

In [319]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.5625

In [358]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.5625

In [321]:
#KFOLD
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [322]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]

In [323]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [324]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.515625

In [325]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

0.5078125

In [357]:
finalm = get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)
finalm

0.5625

In [326]:
from sklearn.model_selection import cross_val_score

In [329]:
cross_val_score(RandomForestClassifier(n_estimators=100),df_encoded, y_1d,cv=3)

array([0.54716981, 0.49528302, 0.56603774])

In [359]:
#For Random Forest Regression
import pickle
with open('CricketMODEL.pkl', 'wb') as f:
    pickle.dump([rf,X_train], f)